name: Node CI

on:
  pull_request:
    paths:
      - "**"
  push:
    branches: ["feature/backend-nodejs"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - run: npm ci
      - run: npm test
      - run: npm run build
